//  const data =[
//     {
//         featureImage:"https://i.ibb.co/qdhZH5g/default-name.jpg",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/cXXQKXh/default-name1.jpg",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/zHsk71x/small-cozy-loft-apartment-and-storage-under-stairs.jpg",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/tmsVzq9/street-2262223-1280.jpg",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/kx3byZs/default-namse.jpg",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/HC9DbLQ/cozy-apartment-living-room.jpg",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/JyhDmgh/Banner-Image-3.png",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/27rkQMv/Banner-Image.png",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
//     {
//         featureImage:"https://i.ibb.co/txJj7PY/Banner-Image-1.png",
//         type:"SunnySlope Suites",
//         title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
//         location:"New York City, USA",
//         price:"100000",
//         featuredImage:["https://i.ibb.co/txJj7PY/Banner-Image-1.png","https://i.ibb.co/27rkQMv/Banner-Image.png","https://i.ibb.co/sHhDNGp/45695cd57effe1b761974bb6a32be2c1.jpg","https://i.ibb.co/JyhDmgh/Banner-Image-3.png"],
//         size:"2000 sqft",
//         floor:"Second (out of 6th floor)",
//         bedRoom:"2",
//         bath:"2",
//         balcony:"2",
//         accommodation:"Fully Furnished",
//         condition:"Ready to Move"
//     },
// ]


// import img1 from '/assest/roomOne/1.jpg';
// import img2 from '/assest/roomOne/2.jpg';
// import img3 from '/assest/roomOne/3.jpg';
// import img4 from '/assest/roomOne/4.jpg';
// import img5 from '/assest/roomOne/5.jpg';
// import img6 from '/assest/roomOne/6.jpg';
// import img7 from '/assest/roomTwo/1.jpeg';
// import img8 from '/assest/roomTwo/2.png';
// import img0 from '/assest/roomTwo/3.jpg';
// import img10 from '/assest/roomTwo/4.jpg';


const data =[
    {
        featureImage:"/assest/roomOne/1.jpg",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"100000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'1'
    },
    {
        featureImage:"/assest/roomOne/2.jpg",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"30000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'2'
    },
    {
        featureImage:"/assest/roomOne/3.jpg",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"105000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'3'
    },
    {
        featureImage:"/assest/roomOne/4.jpg",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"80000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'4'
    },
    {
        featureImage:"/assest/roomOne/5.jpg",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"100000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'5'
    },
    {
        featureImage:"/assest/roomOne/6.jpg",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"100000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'6'
    },
    {
        featureImage:"/assest/roomTwo/1.jpeg",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"100000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'7',
    },
    {
        featureImage:"/assest/roomTwo/2.png",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"100000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'8'
    },
    {
        featureImage:"/assest/roomTwo/3.png",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"100000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'9'
    },
    {
        featureImage:"/assest/roomTwo/4.png",
        type:"SunnySlope Suites",
        title:"3 BHK Builder Floor for Sale Ram Bazar Hyderabad",
        location:"New York City, USA",
        price:"100000",
        featuredImage:["/assest/roomTwo/3.png","/assest/roomTwo/4.png","/assest/roomTwo/1.jpeg","/assest/roomOne/4.jpg"],
        size:"2000 sqft",
        floor:"Second (out of 6th floor)",
        bedRoom:"2",
        bath:"2",
        balcony:"2",
        accommodation:"Fully Furnished",
        condition:"Ready to Move",
        id:'10'
    },
]


export default data